fix #61 Update imbalance learn from 0.4.3 to 0.7.0
Remove Keras and keras-text from requirements.txt.
Uses keras from TF instead.
Loading keras twice was the root cause of error
TypeError: duplicate base class Sequence
By imbalalanced learn >0.4.3